### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by brettswift** [jamischarles/atom-todo-show#41]
###  Enter steps to reproduce below:

From cmd-p - I get this error, even after shutting down atom and reloading it. 

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [todo-show](https://github.com/jamischarles/atom-todo-show) package, v0.8.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

TypeError: undefined is not a function
  at ShowTodoView.module.exports.ShowTodoView.fetchRegexItem (/Users/bswift/.homesick/repos/dotfiles/home/.atom/packages/todo-show/lib/show-todo-view.coffee:148:27)
  at ShowTodoView.module.exports.ShowTodoView.renderTodos (/Users/bswift/.homesick/repos/dotfiles/home/.atom/packages/todo-show/lib/show-todo-view.coffee:176:18)
  at /Users/bswift/.homesick/repos/dotfiles/home/.atom/packages/todo-show/lib/show-todo.coffee:80:22
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:509:49
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

### Commands

```
     -0:01.9 command-palette:toggle (input.hidden-input)
     -0:00.1 core:confirm (input.hidden-input)
     -0:00.0 todo-show:find-in-project (input.hidden-input)
```

### Config

```
{}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v0.21.0
file-icons, v1.4.2
language-puppet, v0.10.0
linter-puppet-lint, v0.2.3
linter-shellcheck, v0.0.6
todo-show, v0.8.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by jamischarles** [comment]
Do you get this same error when you find the todo show command from the
command pallette? (Menu)

**Comment by jamischarles** [comment]
Meaning when you don't use the keystroke?

**Comment by brettswift** [comment]
Unfortunately yea.  Same error.  

I've used this successfully before, not sure what changed.   My work macbook has no issues.   I know that I did install the `Task List` plugin before seeing this error.  That could be a red herring though.

**Comment by MRodalgaard** [comment]
Can anyone reproduce this?

**Comment by mrodalgaard** [comment]
I do not think this still exists after Atom 1.0 release. Correct me if I'm wrong!

**Comment by GinoHereIam** [comment]
I reproduced with following line:
# TODO Fix all print's to <b>useful</b> logger output.

**Comment by GinoHereIam** [comment]
I still get this issue, do you want to get the stacktrace?

**Comment by GinoHereIam** [comment]
I updated Atom. Now works fine!
