### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by gordio** [jamischarles/atom-todo-show#82]
1. Install Plugin

**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [task-list](https://github.com/kenwheeler/task-list) package, v0.7.0

### Stack Trace

Failed to load the task-list package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\Gordienko\.atom\packages\task-list\lib\task-list-view.coffee:1:1)
  at C:\Users\Gordienko\.atom\packages\task-list\lib\task-list-view.coffee:6:3
  at Object.<anonymous> (C:\Users\Gordienko\.atom\packages\task-list\lib\task-list-view.coffee:124:5)
  at Object.<anonymous> (C:\Users\Gordienko\.atom\packages\task-list\lib\task-list-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Gordienko\.atom\packages\task-list\lib\task-list.coffee:1:16)
  at Object.<anonymous> (C:\Users\Gordienko\.atom\packages\task-list\lib\task-list.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:725:34)
  at C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:176:28
  at Package.module.exports.Package.measure (C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
  at Package.module.exports.Package.load (C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:473:30)
  at C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
  at exit (C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
  at triggerExitCallback (C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Gordienko\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -5:28.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:28.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:23.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -5:22.2.0 core:paste (atom-text-editor.editor.is-focused)
  2x -5:16.1.0 core:cut (atom-text-editor.editor.is-focused)
  2x -5:04.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:57.4.0 core:cut (atom-text-editor.editor.is-focused)
     -4:54.1.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -4:41.3.0 core:copy (atom-text-editor.editor.is-focused)
     -4:39.9.0 core:paste (atom-text-editor.editor.is-focused)
     -4:34.7.0 core:save (atom-text-editor.editor.is-focused)
     -4:22.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -4:18.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:18.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:17.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -3:17.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "metrics"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autohide-tree-view, v0.25.1
color-picker, v2.0.13
minimap, v4.16.0
omni-ruler, v0.4.2
task-list, v0.7.0
terminal-plus, v0.13.0

# Dev
No dev packages
```

**Comment by mrodalgaard** [comment]
Hi @gordio,

This error you are seeing are not thrown from the todo-show package but from a package named [task-list](https://github.com/kenwheeler/task-list). So there are not much I can do about that :)
